<?php

use Laminas\Mvc\Plugin\FlashMessenger\View\Helper\FlashMessenger;

$flash = new FlashMessenger();
    $flash->setMessageOpenFormat(
        '<div%s role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                          <div>'
    )
        ->setMessageSeparatorString('<div></div>')
        ->setMessageCloseString('<div></div>')
    ;
?>

<?php
    echo $flash->render('success',['alert', 'alert-dismissible', 'alert-success']);
?>
